"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const{handler}=require("../netlify/functions/paypal-webhook");
const originalFetch=global.fetch,originalEnv={...process.env};
function paypalRequest(body,extra={}){return{httpMethod:"POST",body:JSON.stringify(body),headers:{"paypal-auth-algo":"SHA256withRSA","paypal-cert-url":"https://api.paypal.com/cert.pem","paypal-transmission-id":"transmission-1","paypal-transmission-sig":"signature","paypal-transmission-time":"2026-09-21T10:00:00Z"},...extra}}
function configure(){process.env.PAYPAL_ENV="sandbox";process.env.PAYPAL_CLIENT_ID="sandbox-client";process.env.PAYPAL_CLIENT_SECRET="sandbox-secret";process.env.PAYPAL_WEBHOOK_ID="sandbox-webhook";process.env.LAZYTV_GS_URL="https://script.google.com/macros/s/example/exec";process.env.LAZYTV_INTERNAL_SECRET="internal-secret"}
test.afterEach(()=>{global.fetch=originalFetch;process.env={...originalEnv}});
test("rejects non-POST requests",async()=>{const result=await handler({httpMethod:"GET",headers:{}});assert.equal(result.statusCode,405);assert.equal(JSON.parse(result.body).error,"METHOD_NOT_ALLOWED")});
test("verifies with PayPal and forwards an acknowledged event",async()=>{configure();const calls=[];global.fetch=async(url,options)=>{calls.push({url:String(url),options});if(calls.length===1)return new Response(JSON.stringify({access_token:"token"}),{status:200});if(calls.length===2)return new Response(JSON.stringify({verification_status:"SUCCESS"}),{status:200});return new Response(JSON.stringify({ok:true,event_id:"evt-1"}),{status:200})};const result=await handler(paypalRequest({id:"evt-1",event_type:"BILLING.SUBSCRIPTION.ACTIVATED"})),body=JSON.parse(result.body);assert.equal(result.statusCode,200);assert.equal(body.forwarded,true);assert.equal(calls.length,3);const forwarded=JSON.parse(calls[2].options.body);assert.equal(forwarded.action,"paypalverified");assert.equal(forwarded.internal_secret,"internal-secret");assert.equal(new URL(calls[2].url).searchParams.get("action"),"paypalverified")});
test("supports Netlify base64 request bodies",async()=>{configure();let count=0;global.fetch=async()=>{count+=1;if(count===1)return new Response(JSON.stringify({access_token:"token"}),{status:200});if(count===2)return new Response(JSON.stringify({verification_status:"SUCCESS"}),{status:200});return new Response(JSON.stringify({ok:true}),{status:200})};const event={id:"evt-base64",event_type:"PAYMENT.SALE.COMPLETED"},request=paypalRequest(event,{body:Buffer.from(JSON.stringify(event)).toString("base64"),isBase64Encoded:true});assert.equal((await handler(request)).statusCode,200)});
test("does not forward invalid PayPal signatures",async()=>{configure();let count=0;global.fetch=async()=>{count+=1;if(count===1)return new Response(JSON.stringify({access_token:"token"}),{status:200});return new Response(JSON.stringify({verification_status:"FAILURE"}),{status:200})};const result=await handler(paypalRequest({id:"evt-bad",event_type:"PAYMENT.SALE.DENIED"}));assert.equal(result.statusCode,400);assert.equal(JSON.parse(result.body).error,"INVALID_PAYPAL_SIGNATURE");assert.equal(count,2)});
test("requires PayPal transmission headers before network calls",async()=>{configure();let called=false;global.fetch=async()=>{called=true};const request=paypalRequest({id:"evt-missing",event_type:"TEST"});delete request.headers["paypal-transmission-sig"];const result=await handler(request);assert.equal(result.statusCode,400);assert.equal(JSON.parse(result.body).error,"MISSING_PAYPAL_HEADERS");assert.equal(called,false)});
test("fails when Apps Script returns 200 without ok true",async()=>{configure();let count=0;global.fetch=async()=>{count+=1;if(count===1)return new Response(JSON.stringify({access_token:"token"}),{status:200});if(count===2)return new Response(JSON.stringify({verification_status:"SUCCESS"}),{status:200});return new Response(JSON.stringify({ok:false,error:"BAD_SECRET"}),{status:200})};const result=await handler(paypalRequest({id:"evt-rejected",event_type:"BILLING.SUBSCRIPTION.CANCELLED"}));assert.equal(result.statusCode,502);assert.equal(JSON.parse(result.body).error,"APPS_SCRIPT_REJECTED_EVENT")});
