package de.lazytv.pro.live;
import de.lazytv.pro.activation.ActivationGuard;import android.app.*;import android.content.pm.ActivityInfo;import android.net.Uri;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;import androidx.media3.common.*;import androidx.media3.common.util.UnstableApi;import androidx.media3.datasource.*;import androidx.media3.exoplayer.*;import androidx.media3.exoplayer.source.*;import androidx.media3.ui.PlayerView;import de.lazytv.pro.R;import de.lazytv.pro.catalog.*;import de.lazytv.pro.playlist.*;
@UnstableApi public class LiveTvActivity extends Activity{
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final CatalogEngine engine=new CatalogEngine();private Playlist p;private Catalog catalog;private ExoPlayer player;private DefaultHttpDataSource.Factory http;private PlayerView playerView;private Spinner countrySpinner;private ListView categoriesView,channelsView,overlayCategories,overlayChannels;private TextView title,epg,status;private ProgressBar loading;private EditText search;private View root,leftPanel,channelPanel,info,overlay;private FavoritesStore favorites;private List<CountryGroup> countries=new ArrayList<>();private List<Category> categories=new ArrayList<>();private List<StreamItem> channels=new ArrayList<>(),shown=new ArrayList<>();private StreamItem current;private CountryGroup country;private Category category;private boolean fullscreen,overlayOpen;
 protected void onCreate(Bundle b){super.onCreate(b);if(!ActivationGuard.enforce(this))return;setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);setContentView(R.layout.activity_live_tv);p=new PlaylistStorage(this).get(getIntent().getStringExtra("playlist_id"));if(p==null){finish();return;}favorites=new FavoritesStore(this);bind();initPlayer();load();}
 private void bind(){root=findViewById(R.id.live_root);leftPanel=findViewById(R.id.live_left_panel);channelPanel=findViewById(R.id.live_channel_panel);info=findViewById(R.id.live_info);overlay=findViewById(R.id.live_overlay);playerView=findViewById(R.id.live_player);countrySpinner=findViewById(R.id.live_country_spinner);categoriesView=findViewById(R.id.live_categories);channelsView=findViewById(R.id.live_channels);overlayCategories=findViewById(R.id.overlay_categories);overlayChannels=findViewById(R.id.overlay_channels);title=findViewById(R.id.live_title);epg=findViewById(R.id.live_epg);status=findViewById(R.id.live_status);search=findViewById(R.id.live_search);loading=findViewById(R.id.live_loading);
  countrySpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> a,View v,int pos,long id){selectCountry(pos);}public void onNothingSelected(AdapterView<?> a){}});categoriesView.setOnItemClickListener((a,v,pos,id)->selectCategory(pos,false));channelsView.setOnItemClickListener((a,v,pos,id)->play(pos,false));overlayCategories.setOnItemClickListener((a,v,pos,id)->selectCategory(pos,true));overlayChannels.setOnItemClickListener((a,v,pos,id)->play(pos,true));
  findViewById(R.id.live_favorite).setOnClickListener(v->{if(current!=null){boolean x=favorites.toggle(p.getId(),current);((Button)v).setText(x?"★ Favorite":"☆ Favorite");}});
  findViewById(R.id.live_fullscreen).setOnClickListener(v->setFullscreen(true));
  search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int b,int c){filter(s.toString());}});
  playerView.setOnClickListener(v->{if(fullscreen)showOverlay();});
 }
 private void initPlayer(){http=new DefaultHttpDataSource.Factory().setConnectTimeoutMs(12000).setReadTimeoutMs(20000).setAllowCrossProtocolRedirects(true);DefaultDataSource.Factory ds=new DefaultDataSource.Factory(this,http);player=new ExoPlayer.Builder(this).setMediaSourceFactory(new DefaultMediaSourceFactory(ds)).build();playerView.setPlayer(player);player.addListener(new Player.Listener(){@Override public void onPlaybackStateChanged(int s){loading.setVisibility(s==Player.STATE_BUFFERING?View.VISIBLE:View.GONE);}@Override public void onPlayerError(PlaybackException e){loading.setVisibility(View.GONE);}});}
 private void load(){worker.execute(()->{try{Catalog c=engine.load(this,p);runOnUiThread(()->{catalog=c;countries=CountryResolver.groups(c.categories(CatalogType.LIVE));countrySpinner.setAdapter(spinnerAdapter(countryLabels()));if(!countries.isEmpty()){countrySpinner.setSelection(0);countrySpinner.requestFocus();}});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,e.getMessage()==null?"Catalog error":e.getMessage(),Toast.LENGTH_LONG).show());}});}
 private List<String> countryLabels(){List<String>x=new ArrayList<>();for(CountryGroup g:countries)x.add(g.label+"  ("+g.categories.size()+")");return x;}
 private List<String> categoryLabels(){List<String>x=new ArrayList<>();for(Category c:categories)x.add(CountryResolver.categoryLabel(c.name)+"  ("+catalog.items(CatalogType.LIVE,c.id).size()+")");return x;}
 private void selectCountry(int pos){if(pos<0||pos>=countries.size())return;country=countries.get(pos);categories=new ArrayList<>(country.categories);List<String>x=categoryLabels();categoriesView.setAdapter(adapter(x));overlayCategories.setAdapter(adapter(x));if(!x.isEmpty()){categoriesView.setSelection(0);categoriesView.requestFocus();}}
 private void selectCategory(int pos,boolean fromOverlay){if(pos<0||pos>=categories.size())return;category=categories.get(pos);channels=catalog.items(CatalogType.LIVE,category.id);filter("");if(fromOverlay){overlayChannels.requestFocus();if(!shown.isEmpty())overlayChannels.setSelection(0);}else{channelsView.requestFocus();if(!shown.isEmpty())channelsView.setSelection(0);}}
 private void filter(String q){q=q==null?"":q.trim().toLowerCase(Locale.ROOT);shown=new ArrayList<>();for(StreamItem i:channels)if(q.isEmpty()||(i.name!=null&&i.name.toLowerCase(Locale.ROOT).contains(q)))shown.add(i);List<String>x=channelLabels();channelsView.setAdapter(adapter(x));overlayChannels.setAdapter(adapter(x));}
 private List<String> channelLabels(){List<String>x=new ArrayList<>();for(int n=0;n<shown.size();n++){StreamItem i=shown.get(n);String star=favorites.contains(p.getId(),i)?" ★":"";x.add(String.format(Locale.US,"%03d  %s%s",n+1,i.name,star));}return x;}
 private void play(int pos,boolean fromOverlay){if(pos<0||pos>=shown.size())return;StreamItem item=shown.get(pos);loading.setVisibility(View.VISIBLE);worker.execute(()->{try{ResolvedStream r=engine.resolveStream(p,item);runOnUiThread(()->{playResolved(item,r);if(fromOverlay){hideOverlay();if(!fullscreen)setFullscreen(true);}else setFullscreen(true);});}catch(Exception e){runOnUiThread(()->{loading.setVisibility(View.GONE);Toast.makeText(this,"Stream error",Toast.LENGTH_SHORT).show();});}});}
 private void playResolved(StreamItem item,ResolvedStream r){current=item;http.setDefaultRequestProperties(r.headers);MediaItem.Builder m=new MediaItem.Builder().setUri(Uri.parse(r.url));String u=r.url.toLowerCase(Locale.US);if(u.contains(".m3u8"))m.setMimeType(MimeTypes.APPLICATION_M3U8);else if(u.contains(".ts"))m.setMimeType(MimeTypes.VIDEO_MP2T);else if(u.contains(".mp4"))m.setMimeType(MimeTypes.VIDEO_MP4);player.setMediaItem(m.build(),true);player.prepare();player.play();title.setText(item.name);String now=r.metadata.get("epg_now"),next=r.metadata.get("epg_next");epg.setText((now==null?"":"Now: "+now)+(next==null?"":"\nNext: "+next));((Button)findViewById(R.id.live_favorite)).setText(favorites.contains(p.getId(),item)?"★ Favorite":"☆ Favorite");}
 private ArrayAdapter<String> spinnerAdapter(List<String>x){return new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,x){public View getView(int p,View v,android.view.ViewGroup g){TextView t=(TextView)super.getView(p,v,g);t.setTextColor(android.graphics.Color.WHITE);t.setTextSize(15);t.setSingleLine(true);t.setPadding(10,8,8,8);return t;}public View getDropDownView(int p,View v,android.view.ViewGroup g){TextView t=(TextView)super.getDropDownView(p,v,g);t.setTextColor(android.graphics.Color.WHITE);t.setBackgroundColor(android.graphics.Color.rgb(7,21,34));t.setTextSize(16);t.setPadding(16,14,16,14);return t;}};}\n private ArrayAdapter<String> adapter(List<String>x){return new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,x){public View getView(int p,View v,android.view.ViewGroup g){TextView t=(TextView)super.getView(p,v,g);t.setTextColor(android.graphics.Color.WHITE);t.setTextSize(14);t.setSingleLine(true);t.setEllipsize(android.text.TextUtils.TruncateAt.END);t.setPadding(10,12,8,12);return t;}};}
 private void setFullscreen(boolean on){fullscreen=on;if(on){leftPanel.setVisibility(View.GONE);channelPanel.setVisibility(View.GONE);info.setVisibility(View.GONE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);playerView.requestFocus();}else{hideOverlay();leftPanel.setVisibility(View.VISIBLE);channelPanel.setVisibility(View.VISIBLE);info.setVisibility(View.VISIBLE);getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);if(!shown.isEmpty())channelsView.requestFocus();else if(category!=null)categoriesView.requestFocus();else countrySpinner.requestFocus();}}
 private void showOverlay(){if(!fullscreen)return;overlayOpen=true;overlay.setVisibility(View.VISIBLE);FrameLayout.LayoutParams lp=(FrameLayout.LayoutParams)overlay.getLayoutParams();lp.width=(int)(getResources().getDisplayMetrics().widthPixels*.62f);overlay.setLayoutParams(lp);if(category!=null){overlayCategories.setAdapter(adapter(categoryLabels()));overlayChannels.setAdapter(adapter(channelLabels()));overlayChannels.requestFocus();}else overlayCategories.requestFocus();}
 private void hideOverlay(){overlayOpen=false;overlay.setVisibility(View.GONE);if(fullscreen)playerView.requestFocus();}
 @Override public void onBackPressed(){if(overlayOpen){hideOverlay();return;}if(fullscreen){setFullscreen(false);return;}super.onBackPressed();}
 @Override public boolean dispatchKeyEvent(KeyEvent e){if(e.getAction()==KeyEvent.ACTION_DOWN&&fullscreen&&!overlayOpen&&(e.getKeyCode()==KeyEvent.KEYCODE_DPAD_CENTER||e.getKeyCode()==KeyEvent.KEYCODE_ENTER)){showOverlay();return true;}return super.dispatchKeyEvent(e);}
 protected void onDestroy(){if(player!=null){playerView.setPlayer(null);player.release();}worker.shutdownNow();engine.close();super.onDestroy();}
}