package de.lazytv.pro.live;
import de.lazytv.pro.activation.ActivationGuard;import android.app.*;import android.content.pm.ActivityInfo;import android.net.Uri;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;import androidx.media3.common.*;import androidx.media3.common.util.UnstableApi;import androidx.media3.datasource.*;import androidx.media3.exoplayer.*;import androidx.media3.exoplayer.source.*;import androidx.media3.ui.PlayerView;import de.lazytv.pro.R;import de.lazytv.pro.catalog.*;import de.lazytv.pro.playlist.*;
@UnstableApi public class LiveTvActivity extends Activity{
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final CatalogEngine engine=new CatalogEngine();private Playlist p;private Catalog catalog;private ExoPlayer player;private DefaultHttpDataSource.Factory http;private PlayerView playerView;private ListView countriesView,categoriesView,channelsView;private TextView title,epg,status;private EditText search;private FavoritesStore favorites;private List<CountryGroup> countries=new ArrayList<>();private List<Category> categories=new ArrayList<>();private List<StreamItem> channels=new ArrayList<>(),shown=new ArrayList<>();private StreamItem current;private CountryGroup country;private Category category;private boolean fullscreen;
 protected void onCreate(Bundle b){super.onCreate(b);if(!ActivationGuard.enforce(this))return;setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);setContentView(R.layout.activity_live_tv);p=new PlaylistStorage(this).get(getIntent().getStringExtra("playlist_id"));if(p==null){finish();return;}favorites=new FavoritesStore(this);bind();initPlayer();load();}
 private void bind(){playerView=findViewById(R.id.live_player);countriesView=findViewById(R.id.live_countries);categoriesView=findViewById(R.id.live_categories);channelsView=findViewById(R.id.live_channels);title=findViewById(R.id.live_title);epg=findViewById(R.id.live_epg);status=findViewById(R.id.live_status);search=findViewById(R.id.live_search);countriesView.setOnItemClickListener((a,v,pos,id)->selectCountry(pos));categoriesView.setOnItemClickListener((a,v,pos,id)->selectCategory(pos));channelsView.setOnItemClickListener((a,v,pos,id)->play(pos));findViewById(R.id.live_favorite).setOnClickListener(v->{if(current!=null){boolean x=favorites.toggle(p.getId(),current);((Button)v).setText(x?"★ Favorite":"☆ Favorite");}});findViewById(R.id.live_fullscreen).setOnClickListener(v->setFullscreen(true));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int b,int c){filter(s.toString());}});}
 private void initPlayer(){http=new DefaultHttpDataSource.Factory().setConnectTimeoutMs(12000).setReadTimeoutMs(20000).setAllowCrossProtocolRedirects(true);DefaultDataSource.Factory ds=new DefaultDataSource.Factory(this,http);player=new ExoPlayer.Builder(this).setMediaSourceFactory(new DefaultMediaSourceFactory(ds)).build();playerView.setPlayer(player);}
 private void load(){status.setText("Loading Live TV…");worker.execute(()->{try{Catalog c=engine.load(this,p);runOnUiThread(()->{catalog=c;countries=CountryResolver.groups(c.categories(CatalogType.LIVE));countriesView.setAdapter(strings(countryLabels()));status.setText(countries.size()+" country groups");if(!countries.isEmpty()){countriesView.setSelection(0);countriesView.requestFocus();}});}catch(Exception e){runOnUiThread(()->status.setText(e.getMessage()==null?"Catalog error":e.getMessage()));}});}
 private List<String> countryLabels(){List<String>x=new ArrayList<>();for(CountryGroup g:countries)x.add(g.label+"  ("+g.categories.size()+")");return x;}
 private void selectCountry(int pos){if(pos<0||pos>=countries.size())return;country=countries.get(pos);categories=new ArrayList<>(country.categories);List<String>x=new ArrayList<>();for(Category c:categories)x.add(CountryResolver.categoryLabel(c.name)+"  ("+catalog.items(CatalogType.LIVE,c.id).size()+")");categoriesView.setAdapter(strings(x));if(!x.isEmpty()){categoriesView.setSelection(0);categoriesView.requestFocus();}}
 private void selectCategory(int pos){if(pos<0||pos>=categories.size())return;category=categories.get(pos);channels=catalog.items(CatalogType.LIVE,category.id);filter(search.getText().toString());if(!shown.isEmpty()){channelsView.setSelection(0);channelsView.requestFocus();}}
 private void filter(String q){q=q==null?"":q.trim().toLowerCase(Locale.ROOT);shown=new ArrayList<>();for(StreamItem i:channels)if(q.isEmpty()||(i.name!=null&&i.name.toLowerCase(Locale.ROOT).contains(q)))shown.add(i);List<String>x=new ArrayList<>();for(int n=0;n<shown.size();n++)x.add(String.format(Locale.US,"%03d  %s",n+1,shown.get(n).name));channelsView.setAdapter(strings(x));status.setText(shown.size()+" channels");}
 private void play(int pos){if(pos<0||pos>=shown.size())return;StreamItem item=shown.get(pos);status.setText("Resolving "+item.name+"…");worker.execute(()->{try{ResolvedStream r=engine.resolveStream(p,item);runOnUiThread(()->playResolved(item,r));}catch(Exception e){runOnUiThread(()->status.setText("Stream error"));}});}
 private void playResolved(StreamItem item,ResolvedStream r){current=item;http.setDefaultRequestProperties(r.headers);MediaItem.Builder m=new MediaItem.Builder().setUri(Uri.parse(r.url));String u=r.url.toLowerCase(Locale.US);if(u.contains(".m3u8"))m.setMimeType(MimeTypes.APPLICATION_M3U8);else if(u.contains(".ts"))m.setMimeType(MimeTypes.VIDEO_MP2T);else if(u.contains(".mp4"))m.setMimeType(MimeTypes.VIDEO_MP4);player.setMediaItem(m.build(),true);player.prepare();player.play();title.setText(item.name);String now=r.metadata.get("epg_now"),next=r.metadata.get("epg_next");epg.setText((now==null?"":"Now: "+now)+(next==null?"":"\nNext: "+next));((Button)findViewById(R.id.live_favorite)).setText(favorites.contains(p.getId(),item)?"★ Favorite":"☆ Favorite");status.setText("Playing");}
 private ArrayAdapter<String> strings(List<String>x){return new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,x){public View getView(int p,View v,android.view.ViewGroup g){TextView t=(TextView)super.getView(p,v,g);t.setTextColor(android.graphics.Color.WHITE);t.setTextSize(14);t.setPadding(10,10,10,10);return t;}};}
 private void setFullscreen(boolean on){fullscreen=on;View left=countriesView.getParent() instanceof View?(View)countriesView.getParent():countriesView;View cats=categoriesView.getParent() instanceof View?(View)categoriesView.getParent():categoriesView;View chans=channelsView.getParent() instanceof View?(View)channelsView.getParent():channelsView;left.setVisibility(on?View.GONE:View.VISIBLE);cats.setVisibility(on?View.GONE:View.VISIBLE);chans.setVisibility(on?View.GONE:View.VISIBLE);search.setVisibility(on?View.GONE:View.VISIBLE);findViewById(R.id.live_status).setVisibility(on?View.GONE:View.VISIBLE);findViewById(R.id.live_info).setVisibility(on?View.GONE:View.VISIBLE);if(on){getWindow().getDecorView().setSystemUiVisibility(5894);playerView.requestFocus();}else{getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);channelsView.requestFocus();}}
 @Override public void onBackPressed(){if(fullscreen){setFullscreen(false);return;}super.onBackPressed();}
 @Override public boolean dispatchKeyEvent(KeyEvent e){if(e.getAction()==KeyEvent.ACTION_DOWN&&fullscreen&&(e.getKeyCode()==KeyEvent.KEYCODE_DPAD_CENTER||e.getKeyCode()==KeyEvent.KEYCODE_ENTER)){setFullscreen(false);return true;}return super.dispatchKeyEvent(e);}
 protected void onDestroy(){if(player!=null){playerView.setPlayer(null);player.release();}worker.shutdownNow();engine.close();super.onDestroy();}
}