package de.lazytv.pro.catalog;
import de.lazytv.pro.activation.ActivationGuard;
import android.app.*;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;import de.lazytv.pro.R;import de.lazytv.pro.playlist.*;import de.lazytv.pro.player.PlayerLauncher;
public class CatalogActivity extends Activity{public static final String EXTRA_PLAYLIST_ID="playlist_id";private final ExecutorService pool=Executors.newSingleThreadExecutor();private Playlist p;private Catalog catalog;private final CatalogEngine engine=new CatalogEngine();private CatalogType type=CatalogType.LIVE;private String selectedCategory=null;private CatalogAdapter adapter;private LinearLayout cats;private TextView status,title;
protected void onCreate(Bundle b){super.onCreate(b);if(!ActivationGuard.enforce(this))return;setContentView(R.layout.activity_catalog);PlaylistStorage s=new PlaylistStorage(this);p=s.get(getIntent().getStringExtra(EXTRA_PLAYLIST_ID));if(p==null){Toast.makeText(this,"Playlist nuk u gjet",Toast.LENGTH_LONG).show();finish();return;}s.setActive(p.getId());title=findViewById(R.id.catalog_title);status=findViewById(R.id.catalog_status);cats=findViewById(R.id.category_bar);adapter=new CatalogAdapter();((ListView)findViewById(R.id.catalog_list)).setAdapter(adapter);((ListView)findViewById(R.id.catalog_list)).setOnItemClickListener((a,v,pos,id)->resolveAndShow(adapter.getItem(pos)));findViewById(R.id.tab_live).setOnClickListener(v->show(CatalogType.LIVE));findViewById(R.id.tab_movies).setOnClickListener(v->show(CatalogType.MOVIES));findViewById(R.id.tab_series).setOnClickListener(v->show(CatalogType.SERIES));title.setText(p.getName());load();}
private void load(){status.setText("Duke ngarkuar katalogun…");findViewById(R.id.catalog_progress).setVisibility(View.VISIBLE);pool.execute(()->{try{Catalog c=engine.load(this,p);runOnUiThread(()->{catalog=c;findViewById(R.id.catalog_progress).setVisibility(View.GONE);show(CatalogType.LIVE);});}catch(Exception e){runOnUiThread(()->{findViewById(R.id.catalog_progress).setVisibility(View.GONE);status.setText(e.getMessage()==null?"Gabim gjatë ngarkimit":e.getMessage());});}});}
private void show(CatalogType t){type=t;selectedCategory=null;if(catalog==null)return;cats.removeAllViews();List<Category> cs=catalog.categories(t);Button all=button("Të gjitha");all.setOnClickListener(v->items(null));cats.addView(all);for(Category c:cs){Button b=button(c.name);b.setOnClickListener(v->items(c.id));cats.addView(b);}items(null);}
private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private void items(String cat){selectedCategory=cat;List<StreamItem>x=catalog.items(type,cat);adapter.set(x);status.setText(x.size()+" elemente");}
private void resolveAndShow(StreamItem i){if(i instanceof Series){android.content.Intent x=new android.content.Intent(this,SeriesDetailActivity.class);x.putExtra(SeriesDetailActivity.PLAYLIST,p.getId());x.putExtra(SeriesDetailActivity.SERIES_ID,i.id);x.putExtra(SeriesDetailActivity.SERIES_NAME,i.name);x.putExtra(SeriesDetailActivity.SERIES_LOGO,i.logo);x.putExtra(SeriesDetailActivity.SERIES_CAT,i.categoryId);startActivity(x);return;}status.setText("Duke përgatitur stream-in…");pool.execute(()->{try{ResolvedStream rs=engine.resolveStream(p,i);runOnUiThread(()->{status.setText("Stream gati");PlayerLauncher.open(this,p.getId(),i,rs,categoryName(i.categoryId));});}catch(Exception e){runOnUiThread(()->status.setText("Stream-i nuk mund të zgjidhet"));}});} private String categoryName(String id){if(catalog==null||id==null)return"";for(Category c:catalog.categories)if(id.equals(c.id)&&c.type==type)return c.name;return"";}private String safe(String s){return s==null?"":s;}protected void onDestroy(){pool.shutdownNow();engine.close();super.onDestroy();}}
