package de.lazytv.pro.catalog;
import de.lazytv.pro.activation.ActivationGuard;
import android.app.*;import de.lazytv.pro.Base64AssetImage;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;import de.lazytv.pro.R;import de.lazytv.pro.playlist.*;import de.lazytv.pro.player.PlayerLauncher;
public class CatalogActivity extends Activity{
 public static final String EXTRA_PLAYLIST_ID="playlist_id",EXTRA_TYPE="catalog_type";private final ExecutorService pool=Executors.newSingleThreadExecutor();private Playlist p;private Catalog catalog;private final CatalogEngine engine=new CatalogEngine();private CatalogType type=CatalogType.LIVE;private CatalogAdapter adapter;private TextView status,title,breadcrumb;private GridView list;private EditText search;private FavoritesStore favorites;private int level=0;private CountryGroup country;private Category category;private boolean favoritesMode=false;private List<CountryGroup> countries=new ArrayList<>();private List<Category> visibleCategories=new ArrayList<>();private List<StreamItem> visibleItems=new ArrayList<>();
 protected void onCreate(Bundle b){super.onCreate(b);if(!ActivationGuard.enforce(this))return;setContentView(R.layout.activity_catalog);PlaylistStorage s=new PlaylistStorage(this);p=s.get(getIntent().getStringExtra(EXTRA_PLAYLIST_ID));if(p==null){Toast.makeText(this,"Playlist nuk u gjet",Toast.LENGTH_LONG).show();finish();return;}s.setActive(p.getId());favorites=new FavoritesStore(this);title=findViewById(R.id.catalog_title);status=findViewById(R.id.catalog_status);breadcrumb=findViewById(R.id.catalog_breadcrumb);search=findViewById(R.id.catalog_search);list=findViewById(R.id.catalog_list);adapter=new CatalogAdapter();list.setAdapter(adapter);list.setOnItemClickListener((a,v,pos,id)->click(pos));list.setOnItemLongClickListener((a,v,pos,id)->{if(level==2&&pos<visibleItems.size()){toggleFavorite(visibleItems.get(pos));return true;}return false;});findViewById(R.id.tab_live).setOnClickListener(v->showType(CatalogType.LIVE));findViewById(R.id.tab_movies).setOnClickListener(v->showType(CatalogType.MOVIES));findViewById(R.id.tab_series).setOnClickListener(v->showType(CatalogType.SERIES));findViewById(R.id.tab_favorites).setOnClickListener(v->showFavorites());search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){applySearch(s.toString());}public void afterTextChanged(Editable e){}});Base64AssetImage.load(this,(ImageView)findViewById(R.id.catalog_progress),"lazytv_home.webp.b64");title.setText(p.getName());String requested=getIntent().getStringExtra(EXTRA_TYPE);if("MOVIES".equals(requested))type=CatalogType.MOVIES;else if("SERIES".equals(requested))type=CatalogType.SERIES;load();}
 private void load(){status.setText("Duke ngarkuar katalogun…");findViewById(R.id.catalog_progress).setVisibility(View.VISIBLE);pool.execute(()->{try{Catalog c=engine.load(this,p);runOnUiThread(()->{catalog=c;findViewById(R.id.catalog_progress).setVisibility(View.GONE);showType(type);});}catch(Exception e){runOnUiThread(()->{findViewById(R.id.catalog_progress).setVisibility(View.GONE);status.setText(e.getMessage()==null?"Gabim gjatë ngarkimit":e.getMessage());});}});}
 private void showType(CatalogType t){if(catalog==null)return;type=t;favoritesMode=false;country=null;category=null;level=0;search.setText("");countries=CountryResolver.groups(catalog.categories(t));showCountries();}
 private void showCountries(){level=0;adapter.setLabels(labelsCountries());breadcrumb.setText(type.name()+"  ›  COUNTRY");status.setText(countries.size()+" countries / groups");focusList();}
 private List<String> labelsCountries(){List<String>x=new ArrayList<>();for(CountryGroup g:countries)x.add(g.label+"   ("+g.categories.size()+")");return x;}
 private void showCategories(CountryGroup g){country=g;level=1;visibleCategories=new ArrayList<>(g.categories);adapter.setLabels(labelsCategories(visibleCategories));breadcrumb.setText(type.name()+"  ›  "+g.label+"  ›  CATEGORY");status.setText(visibleCategories.size()+" categories");focusList();}
 private List<String> labelsCategories(List<Category> cs){List<String>x=new ArrayList<>();for(Category c:cs){int n=catalog.items(type,c.id).size();x.add(CountryResolver.categoryLabel(c.name)+"   ("+n+")");}return x;}
 private void showItems(Category c){category=c;level=2;visibleItems=catalog.items(type,c.id);adapter.set(visibleItems);breadcrumb.setText(type.name()+"  ›  "+country.label+"  ›  "+CountryResolver.categoryLabel(c.name));status.setText(visibleItems.size()+" items • Long OK/touch për Favorite");focusList();}
 private void click(int pos){if(favoritesMode){if(pos<visibleItems.size())open(visibleItems.get(pos));return;}if(level==0){if(pos<countries.size())showCategories(countries.get(pos));}else if(level==1){if(pos<visibleCategories.size())showItems(visibleCategories.get(pos));}else if(pos<visibleItems.size())open(visibleItems.get(pos));}
 private void open(StreamItem i){if(type==CatalogType.LIVE){android.content.Intent live=new android.content.Intent(this,de.lazytv.pro.live.LiveTvActivity.class);live.putExtra("playlist_id",p.getId());startActivity(live);return;}if(i instanceof Series){android.content.Intent x=new android.content.Intent(this,SeriesDetailActivity.class);x.putExtra(SeriesDetailActivity.PLAYLIST,p.getId());x.putExtra(SeriesDetailActivity.SERIES_ID,i.id);x.putExtra(SeriesDetailActivity.SERIES_NAME,i.name);x.putExtra(SeriesDetailActivity.SERIES_LOGO,i.logo);x.putExtra(SeriesDetailActivity.SERIES_CAT,i.categoryId);startActivity(x);return;}status.setText("Duke përgatitur stream-in…");pool.execute(()->{try{ResolvedStream rs=engine.resolveStream(p,i);runOnUiThread(()->{status.setText("Stream gati");PlayerLauncher.open(this,p.getId(),i,rs,categoryName(i.categoryId));});}catch(Exception e){runOnUiThread(()->status.setText("Stream-i nuk mund të zgjidhet"));}});}
 private void showFavorites(){if(catalog==null)return;favoritesMode=true;level=2;search.setText("");visibleItems=favorites.filter(p.getId(),catalog.items);adapter.set(visibleItems);breadcrumb.setText("★ FAVORITES");status.setText(visibleItems.size()+" favorites");focusList();}
 private void toggleFavorite(StreamItem i){boolean add=favorites.toggle(p.getId(),i);Toast.makeText(this,add?"U shtua te Favorites":"U hoq nga Favorites",Toast.LENGTH_SHORT).show();if(favoritesMode)showFavorites();}
 private void applySearch(String q){if(catalog==null)return;q=q==null?"":q.trim().toLowerCase(Locale.ROOT);if(q.isEmpty()){if(favoritesMode){visibleItems=favorites.filter(p.getId(),catalog.items);adapter.set(visibleItems);}else if(level==0)showCountries();else if(level==1)showCategories(country);else if(category!=null)showItems(category);return;}List<StreamItem> base=favoritesMode?favorites.filter(p.getId(),catalog.items):catalog.items(type,null);List<StreamItem> r=new ArrayList<>();for(StreamItem i:base)if(i.name!=null&&i.name.toLowerCase(Locale.ROOT).contains(q))r.add(i);visibleItems=r;level=2;adapter.set(r);breadcrumb.setText((favoritesMode?"★ FAVORITES":type.name())+"  ›  SEARCH");status.setText(r.size()+" results");focusList();}
 private String categoryName(String id){if(catalog==null||id==null)return"";for(Category c:catalog.categories)if(id.equals(c.id)&&c.type==type)return c.name;return"";}
 private void focusList(){if(list.getCount()>0){list.setSelection(0);list.requestFocus();}}
 @Override public void onBackPressed(){if(!search.getText().toString().isEmpty()){search.setText("");return;}if(favoritesMode){showType(type);return;}if(level==2&&country!=null){showCategories(country);return;}if(level==1){showCountries();return;}super.onBackPressed();}
 @Override public boolean dispatchKeyEvent(KeyEvent e){if(e.getAction()==KeyEvent.ACTION_DOWN&&e.getRepeatCount()==0){int k=e.getKeyCode();if(k==KeyEvent.KEYCODE_MENU||k==KeyEvent.KEYCODE_SEARCH){search.requestFocus();return true;}if(k==KeyEvent.KEYCODE_DPAD_LEFT&&list.hasFocus()&&level>0){onBackPressed();return true;}}return super.dispatchKeyEvent(e);} protected void onDestroy(){adapter.close();pool.shutdownNow();engine.close();super.onDestroy();}
}