package de.lazytv.pro.catalog;
import java.util.*;import java.util.regex.*;
public final class CountryResolver{
 private static final Pattern[] P={Pattern.compile("^\\s*\\[([A-Za-z]{2,3})\\]\\s*(.*)$"),Pattern.compile("^\\s*([A-Za-z]{2,3})\\s*[|:•»>-]\\s*(.+)$"),Pattern.compile("^\\s*([A-Za-z]{2,3})\\s+[-–—]\\s+(.+)$"),Pattern.compile("^\\s*[\\p{So}\\s]*([A-Za-z]{2,3})\\s*(?:[|:•»>_\\-]+|\\s+)\\s*(.+)$")};
 private static final Map<String,String>A3=new HashMap<>(),NAMES=new HashMap<>();
 static{for(String a2:Locale.getISOCountries())try{Locale l=new Locale("",a2);A3.put(l.getISO3Country().toUpperCase(Locale.ROOT),a2);NAMES.put(l.getDisplayCountry(Locale.ENGLISH).toUpperCase(Locale.ROOT),a2);}catch(Exception ignored){}alias("KS","KOSOVO","KOSOVA","XK","XKX","KOS");alias("MK","MACEDONIA","NORTH MACEDONIA","MAQEDONIA","MAQEDONIA E VERIUT","MKD");alias("AL","ALBANIA","SHQIPERIA","SHQIPËRIA","ALB");alias("TR","TURKEY","TURKIYE","TURQI","TURQIA","TUR");alias("DE","GERMANY","DEUTSCHLAND","GJERMANIA","DEU");alias("IT","ITALY","ITALIA","ITA");alias("GB","UNITED KINGDOM","GREAT BRITAIN","UK","GBR");alias("US","UNITED STATES","USA");alias("BA","BOSNIA","BOSNIA AND HERZEGOVINA","BIH");alias("RS","SERBIA","SRB");alias("HR","CROATIA","HRV");alias("ME","MONTENEGRO","MNE");alias("SI","SLOVENIA","SVN");alias("AT","AUSTRIA","ÖSTERREICH","AUT");alias("CH","SWITZERLAND","SCHWEIZ","SUISSE","CHE");alias("FR","FRANCE","FRANKREICH","FRA");alias("NL","NETHERLANDS","HOLLAND","NEDERLAND","NLD");alias("BE","BELGIUM","BELGIQUE","BELGIEN","BEL");alias("ES","SPAIN","ESPAÑA","ESP");alias("PT","PORTUGAL","PRT");alias("GR","GREECE","GREEK","GRC");alias("BG","BULGARIA","BGR");alias("RO","ROMANIA","ROU");alias("HU","HUNGARY","HUN");alias("PL","POLAND","POL");alias("CZ","CZECH","CZECHIA","CZE");alias("SK","SLOVAKIA","SVK");alias("UA","UKRAINE","UKR");alias("RU","RUSSIA","RUS");alias("SA","SAUDI","SAUDI ARABIA","KSA","SAU");alias("AE","UAE","UNITED ARAB EMIRATES","ARE");alias("QA","QATAR","QAT");alias("EG","EGYPT","EGY");alias("MA","MOROCCO","MAR");alias("DZ","ALGERIA","DZA");alias("TN","TUNISIA","TUN");}
 private static void alias(String code,String...xs){for(String x:xs)NAMES.put(x,code);}
 private CountryResolver(){}
 public static String key(Category c){if(c!=null&&c.country!=null&&!c.country.trim().isEmpty())return normalize(c.country);return key(c==null?null:c.name);}
 public static String key(String name){if(name==null)return"OTHER";String raw=name.trim(),u=raw.toUpperCase(Locale.ROOT);String fc=flagCode(raw);if(fc!=null)return fc;if(u.contains("EXYU")||u.contains("EX-YU")||u.contains("EX YU"))return"EXYU";for(Pattern p:P){Matcher m=p.matcher(raw);if(m.matches())return normalize(m.group(1));}String direct=NAMES.get(u);if(direct!=null)return direct;
 String cleaned=u.replaceAll("[^\\p{L}\\p{N}]+"," ").trim();String padded=" "+cleaned+" ";
 String best=null;int bestLen=0;
 for(Map.Entry<String,String> e:NAMES.entrySet()){String n=e.getKey();if(n.length()<4)continue;if(padded.contains(" "+n+" ")&&n.length()>bestLen){best=e.getValue();bestLen=n.length();}}
 return best==null?"OTHER":best;}
 private static String flagCode(String s){int first=-1;for(int i=0;i<s.length();){int cp=s.codePointAt(i);if(cp>=0x1F1E6&&cp<=0x1F1FF){if(first>=0){char a=(char)(65+first-0x1F1E6),b=(char)(65+cp-0x1F1E6);String z=normalize(""+a+b);return "OTHER".equals(z)?null:z;}first=cp;}else first=-1;i+=Character.charCount(cp);}return null;}\n private static String normalize(String raw){if(raw==null)return"OTHER";String k=raw.trim().toUpperCase(Locale.ROOT);if(k.contains("EXYU")||k.equals("EX-YU")||k.equals("EX YU"))return"EXYU";String n=NAMES.get(k);if(n!=null)return n;if(k.length()==2){for(String x:Locale.getISOCountries())if(x.equalsIgnoreCase(k))return x.toUpperCase(Locale.ROOT);}String a=A3.get(k);return a==null?"OTHER":a;}
 public static String categoryLabel(String name){if(name==null)return"";for(Pattern p:P){Matcher m=p.matcher(name);if(m.matches()&&!m.group(2).trim().isEmpty())return m.group(2).trim();}return name.trim();}
 private static String flag(String k){if(k==null||k.length()!=2)return"🌐";int a=Character.codePointAt(k,0)-'A'+0x1F1E6,b=Character.codePointAt(k,1)-'A'+0x1F1E6;return new String(Character.toChars(a))+new String(Character.toChars(b));}
 private static String label(String k){if("OTHER".equals(k))return"🌐 Të tjera";if("EXYU".equals(k))return"🌐 EXYU";if("KS".equals(k))return"🇽🇰 Kosova - KS";if("MK".equals(k))return"🇲🇰 Maqedonia e Veriut - MK";if("AL".equals(k))return"🇦🇱 Shqipëria - AL";if("DE".equals(k))return"🇩🇪 Gjermania - DE";if("IT".equals(k))return"🇮🇹 Italia - IT";if("TR".equals(k))return"🇹🇷 Turqia - TR";if("GB".equals(k))return"🇬🇧 Mbretëria e Bashkuar - UK";if("US".equals(k))return"🇺🇸 SHBA - US";Locale l=new Locale("",k);String n=l.getDisplayCountry(new Locale("sq"));if(n==null||n.trim().isEmpty())n=l.getDisplayCountry(Locale.ENGLISH);return flag(k)+" "+n+" - "+k;}
 public static List<CountryGroup> groups(List<Category> categories){LinkedHashMap<String,CountryGroup> map=new LinkedHashMap<>();for(Category c:categories){String k=key(c);CountryGroup g=map.get(k);if(g==null){g=new CountryGroup(k,label(k));map.put(k,g);}g.categories.add(c);}List<CountryGroup> out=new ArrayList<>(map.values());Collections.sort(out,(a,b)->{if("OTHER".equals(a.key))return 1;if("OTHER".equals(b.key))return -1;return a.label.compareToIgnoreCase(b.label);});for(CountryGroup g:out)Collections.sort(g.categories,(a,b)->categoryLabel(a.name).compareToIgnoreCase(categoryLabel(b.name)));return out;}
}