package de.lazytv.pro.catalog;
import org.json.*;import java.util.*;import android.util.Log;import de.lazytv.pro.playlist.Playlist;
public class StalkerCatalogSource {
 private String endpoint="",mac="",token=""; private boolean legacyLoadPhp=false; private Map<String,String> headers=new LinkedHashMap<>(); private long sessionAt=0; private static final long SESSION_MS=20*60*1000L;
 public static class LinkResult{public final String url;public final Map<String,String> headers;LinkResult(String u,Map<String,String>h){url=u;headers=h;}}
 public synchronized void clear(){token="";sessionAt=0;headers.clear();}
 private synchronized void ensure(Playlist p)throws CatalogException{String ep=normalize(p.getUrl()),m=p.getMacAddress().trim();if(!token.isEmpty()&&ep.equals(endpoint)&&m.equals(mac)&&System.currentTimeMillis()-sessionAt<SESSION_MS)return;endpoint=ep;mac=m;headers=new LinkedHashMap<>();headers.put("Cookie","mac="+mac+"; stb_lang=en; timezone=Europe%2FBerlin;");headers.put("X-User-Agent","Model: MAG254; Link: Ethernet");headers.put("Referer",portalReferer(endpoint));headers.put("Origin",portalOrigin(endpoint));headers.put("Accept","*/*");handshake();}
 private void handshake()throws CatalogException{JSONObject h=data(raw("type=stb&action=handshake&token=&prehash=0&JsHttpRequest=1-xml"));token=h.optString("token");if(token.isEmpty())throw new CatalogException("Stalker handshake dështoi: token mungon");headers.put("Authorization","Bearer "+token);sessionAt=System.currentTimeMillis();try{step("profile","type=stb&action=get_profile&JsHttpRequest=1-xml");}catch(Exception e){Log.d("LazyTV-Stalker","STALKER STEP=profile optional failure="+safe(e));}try{step("account","type=account_info&action=get_main_info&JsHttpRequest=1-xml");}catch(Exception e){Log.d("LazyTV-Stalker","STALKER STEP=account optional failure="+safe(e));}}
 private String get(String q)throws CatalogException{try{return raw(q);}catch(CatalogException e){if(!token.isEmpty()){token="";headers.remove("Authorization");handshake();return raw(q);}throw e;}}
 private String raw(String q)throws CatalogException{
  CatalogException last=null;
  for(String ep:endpoints(endpoint)){
   try{String body=HttpClient.get(ep+"?"+q,headers);if(body!=null&&!body.trim().isEmpty()){endpoint=ep;return body;}}
   catch(CatalogException e){last=e;}
  }
  throw last==null?new CatalogException("Stalker portal nuk u përgjigj"):last;
 }
 private java.util.List<String> endpoints(String ep){
  java.util.LinkedHashSet<String> x=new java.util.LinkedHashSet<>();x.add(ep);
  String base=ep.replaceAll("/(portal\\.php|server/load\\.php)$","");
  x.add(base+"/portal.php");x.add(base+"/server/load.php");
  return new java.util.ArrayList<>(x);
 } private String step(String name,String q)throws CatalogException{try{String x=raw(q);Log.d("LazyTV-Stalker","STALKER STEP="+name+" OK host="+host(endpoint));return x;}catch(CatalogException e){Log.e("LazyTV-Stalker","STALKER STEP="+name+" FAIL host="+host(endpoint)+" error="+safe(e));throw e;}}
 public Catalog load(Playlist p)throws CatalogException{ensure(p);Catalog c=new Catalog();load(c,"itv",CatalogType.LIVE);load(c,"vod",CatalogType.MOVIES);try{load(c,"series",CatalogType.SERIES);}catch(CatalogException ignored){}if(c.isEmpty())throw new CatalogException("Portal u lidh, por nuk ktheu përmbajtje të lexueshme");return c;}
 public SeriesDetails loadSeries(Playlist p,Series series)throws CatalogException{ensure(p);SeriesDetails d=new SeriesDetails();String sid=series.id;JSONArray seasons=flexArray(get("type=series&action=get_ordered_list&movie_id="+HttpClient.enc(sid)+"&JsHttpRequest=1-xml"));if(seasons.length()==0)seasons=flexArray(get("type=vod&action=get_ordered_list&movie_id="+HttpClient.enc(sid)+"&JsHttpRequest=1-xml"));for(int i=0;i<seasons.length();i++){JSONObject o=seasons.optJSONObject(i);if(o==null)continue;int sn=o.optInt("season",o.optInt("season_number",i+1));String seasonId=o.optString("id",String.valueOf(sn));d.seasons.add(new Season(seasonId,o.optString("name",o.optString("title","Season "+sn)),sid,sn,o.optString("screenshot_uri",series.logo)));JSONArray embedded=o.optJSONArray("episodes");if(embedded!=null)parseEpisodes(d,embedded,sid,sn,series.logo);else parseEpisodes(d,tryEpisodes(sid,seasonId,sn),sid,sn,series.logo);}if(d.seasons.isEmpty()){JSONArray eps=tryEpisodes(sid,"",0);parseEpisodes(d,eps,sid,0,series.logo);for(Integer sn:d.episodes.keySet())d.seasons.add(new Season(String.valueOf(sn),"Season "+sn,sid,sn,series.logo));}if(d.isEmpty())throw new CatalogException("Portali nuk ktheu sezone ose episode për këtë serial");return d;}
 private JSONArray tryEpisodes(String sid,String seasonId,int sn){String[] qs={"type=series&action=get_ordered_list&movie_id="+HttpClient.enc(sid)+"&season_id="+HttpClient.enc(seasonId)+"&JsHttpRequest=1-xml","type=vod&action=get_ordered_list&movie_id="+HttpClient.enc(sid)+"&season="+sn+"&JsHttpRequest=1-xml"};for(String q:qs)try{JSONArray a=flexArray(get(q));if(a.length()>0)return a;}catch(Exception ignored){}return new JSONArray();}
 private void parseEpisodes(SeriesDetails d,JSONArray a,String sid,int fallback,String cover){for(int i=0;i<a.length();i++){JSONObject e=a.optJSONObject(i);if(e==null)continue;int sn=e.optInt("season",e.optInt("season_number",fallback>0?fallback:1));int en=e.optInt("episode",e.optInt("episode_num",i+1));String id=e.optString("id",e.optString("ch_id"));String cmd=e.optString("cmd",e.optString("url"));Map<String,String> meta=new LinkedHashMap<>();String desc=e.optString("description");if(!desc.isEmpty())meta.put("description",desc);Episode ep=new Episode(id,e.optString("name",e.optString("title","Episode "+en)),sid,"",e.optString("screenshot_uri",e.optString("logo",cover)),cmd,e.optString("container_extension"),e.optString("time",e.optString("duration")),sn,en,meta);d.episodes.computeIfAbsent(sn,k->new ArrayList<>()).add(ep);}}
 public LinkResult resolve(Playlist p,StreamItem item)throws CatalogException{ensure(p);String cmd=item.streamUrl;if(cmd==null||cmd.trim().isEmpty())throw new CatalogException("Portal stream reference mungon");String portalType=item.type==CatalogType.LIVE?"itv":"vod";String q="type="+portalType+"&action=create_link&cmd="+HttpClient.enc(cmd)+"&series="+(item instanceof Episode?"1":"0")+"&forced_storage=undefined&disable_ad=0&download=0&JsHttpRequest=1-xml";JSONObject d=data(get(q));String out=d.optString("cmd",d.optString("url"));out=cleanCmd(out);if(out.isEmpty())throw new CatalogException("Portali nuk ktheu URL për stream-in");Log.d("LazyTV-Stalker","STALKER STEP=create_link OK host="+host(out));Map<String,String> h=new LinkedHashMap<>();h.put("Cookie",headers.get("Cookie"));h.put("X-User-Agent",headers.get("X-User-Agent"));String auth=headers.get("Authorization");if(auth!=null&&!auth.isEmpty())h.put("Authorization",auth);String ref=headers.get("Referer");if(ref!=null)h.put("Referer",ref);return new LinkResult(out,h);}
 private void load(Catalog c,String type,CatalogType ct)throws CatalogException{JSONArray gs=flexArray(step(type+"_genres","type="+type+"&action=get_genres&JsHttpRequest=1-xml"));for(int i=0;i<gs.length();i++){JSONObject g=gs.optJSONObject(i);if(g!=null)c.categories.add(new Category(g.optString("id"),g.optString("title",g.optString("name","Të tjera")),ct));}Set<String>seen=new HashSet<>();for(int page=1;page<=50;page++){String resp=step(type+"_channels_p"+page,"type="+type+"&action=get_ordered_list&p="+page+"&JsHttpRequest=1-xml");JSONObject root=json(resp);JSONObject js=root.optJSONObject("js");if(js==null)js=root.optJSONObject("data");if(js==null)js=root;JSONArray a=js.optJSONArray("data");if(a==null)a=js.optJSONArray("items");if(a==null)a=js.optJSONArray("results");if(a==null){Object direct=root.opt("js");if(direct instanceof JSONArray)a=(JSONArray)direct;}if(a==null||a.length()==0)break;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String id=o.optString("id",o.optString("ch_id"));if(id.isEmpty()||!seen.add(id))continue;c.items.add(CatalogItems.create(id,o.optString("name","Stream"),o.optString("tv_genre_id",o.optString("category_id")),o.optString("logo",o.optString("screenshot_uri")),o.optString("cmd",o.optString("url")),"",ct));}int total=js.optInt("total_items",a.length());if(total>0&&seen.size()>=total)break;}}
 private JSONObject json(String s)throws CatalogException{try{
  String t=s==null?"":s.trim();
  int a=t.indexOf('{'),b=t.lastIndexOf('}');
  if(a>=0&&b>a)t=t.substring(a,b+1);
  if(t.startsWith("\uFEFF"))t=t.substring(1);
  return new JSONObject(t);
 }catch(Exception e){throw new CatalogException("Përgjigje Stalker e pavlefshme",e);}}
 private JSONObject data(String s)throws CatalogException{JSONObject j=json(s);Object x=j.opt("js");if(x instanceof JSONObject)return(JSONObject)x;Object d=j.opt("data");if(d instanceof JSONObject)return(JSONObject)d;return j;}
 private JSONArray flexArray(String s)throws CatalogException{JSONObject j=json(s);Object x=j.opt("js");if(x instanceof JSONArray)return(JSONArray)x;if(x instanceof JSONObject){JSONObject o=(JSONObject)x;JSONArray d=o.optJSONArray("data");if(d!=null)return d;JSONArray a=o.optJSONArray("items");if(a!=null)return a;JSONArray r=o.optJSONArray("results");if(r!=null)return r;}JSONArray d=j.optJSONArray("data");if(d!=null)return d;JSONArray a=j.optJSONArray("items");if(a!=null)return a;return new JSONArray();}
 private String cleanCmd(String s){if(s==null)return"";s=s.trim();if(s.startsWith("ffmpeg "))s=s.substring(7).trim();if(s.startsWith("auto "))s=s.substring(5).trim();int h=s.indexOf("http://"),hs=s.indexOf("https://");int at=h>=0&&hs>=0?Math.min(h,hs):Math.max(h,hs);if(at>0)s=s.substring(at);return s.trim();}
 private String portalOrigin(String ep){try{java.net.URL u=new java.net.URL(ep);return u.getProtocol()+"://"+u.getAuthority();}catch(Exception e){return"";}}\n private String portalReferer(String ep){try{java.net.URL u=new java.net.URL(ep);return u.getProtocol()+"://"+u.getAuthority()+"/c/";}catch(Exception e){return ep;}}
 private String host(String u){try{return new java.net.URL(u).getHost();}catch(Exception e){return"unknown";}}
 private String safe(Exception e){String s=e.getMessage();return s==null?e.getClass().getSimpleName():s.replaceAll("(?i)(token|mac|password|username)=[^&\\s]+","$1=<redacted>");}
 private String normalize(String u){u=u.trim().replace("&amp;","&");int q=u.indexOf('?');if(q>0)u=u.substring(0,q);u=u.replaceAll("/+$","");if(u.endsWith("/portal.php")||u.endsWith("/server/load.php"))return u;if(u.endsWith("/c"))u=u.substring(0,u.length()-2);return u+"/portal.php";}
}