plugins {
    id 'com.android.application'
}

android {
    buildFeatures { buildConfig true }
    namespace 'de.lazytv.pro'
    compileSdk 35

    defaultConfig {
        applicationId 'de.lazytv.pro'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
        buildConfigField 'String', 'ACTIVATION_BASE_URL', '""'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.media3:media3-exoplayer:1.5.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.5.1'
    implementation 'androidx.media3:media3-ui:1.5.1'
}
