package de.lazytv.pro.cms;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;
public class IslamicCatalogActivity extends Activity{
 public static final String EXTRA_CATEGORY="category"; private final ExecutorService pool=Executors.newSingleThreadExecutor(); private GridView grid; private TextView status; private String category;
 static class Item{String id,title,url,poster,type,source;int episode;Item(String i,String t,String u,String p,String ty,int e,String s){id=i;title=t;url=u;poster=p;type=ty;episode=e;source=s;}}
 protected void onCreate(Bundle b){super.onCreate(b);category=getIntent().getStringExtra(EXTRA_CATEGORY); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,14,18,14);root.setBackgroundColor(Color.rgb(6,17,31));TextView h=new TextView(this);h.setText(label(category));h.setTextColor(Color.WHITE);h.setTextSize(25);h.setTypeface(null,1);root.addView(h);status=new TextView(this);status.setText("Duke ngarkuar nga LazyTV CMS…");status.setTextColor(Color.rgb(175,196,216));status.setPadding(0,8,0,10);root.addView(status);grid=new GridView(this);grid.setNumColumns(4);grid.setHorizontalSpacing(12);grid.setVerticalSpacing(12);root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);load();}
 private void load(){pool.execute(()->{try{ArrayList<Item>a=new ArrayList<>();if(IslamicCmsConfig.LECTURES.equals(category)||IslamicCmsConfig.DOCUMENTARIES.equals(category)||IslamicCmsConfig.KIDS.equals(category)||IslamicCmsConfig.SERIES.equals(category))loadSources(a);loadVod(a);runOnUiThread(()->show(a));}catch(Exception e){runOnUiThread(()->status.setText("CMS nuk u ngarkua: "+e.getMessage()));}});}
 private void loadVod(ArrayList<Item>a)throws Exception{for(String[]r:csv(IslamicCmsConfig.csv("VOD"))){if(r.length<12||!"TRUE".equalsIgnoreCase(r[11])||!category.equals(r[4]))continue;int ep=num(r[6]);String p=r[8];if(p==null||p.trim().isEmpty())p=posterForUrl(r[7]);a.add(new Item(r[0],r[1],r[7],p,r[2],ep,"vod"));}}
 private void loadSources(ArrayList<Item>a)throws Exception{for(String[]r:csv(IslamicCmsConfig.csv("YOUTUBE"))){if(r.length<7||!"TRUE".equalsIgnoreCase(r[6])||!category.equals(r[5]))continue;String id=r[3],u=id.startsWith("@")?"https://www.youtube.com/"+id:id.startsWith("PL")?"https://www.youtube.com/playlist?list="+id:"https://www.dailymotion.com/playlist/"+id;a.add(new Item(r[0],r[1],u,posterFor(r[0]),"source",0,"source"));}}
 private void show(ArrayList<Item>raw){ArrayList<Item> items=raw;if(IslamicCmsConfig.SERIES.equals(category)){LinkedHashMap<String,Item>m=new LinkedHashMap<>();for(Item i:raw){String k=seriesKey(i);if(!m.containsKey(k))m.put(k,new Item(k,seriesTitle(i),i.url,(posterFor(k).isEmpty()?i.poster:posterFor(k)),"series",0,i.source));}items=new ArrayList<>(m.values());}final ArrayList<Item> fin=items;grid.setAdapter(new BaseAdapter(){public int getCount(){return fin.size();}public Object getItem(int p){return fin.get(p);}public long getItemId(int p){return p;}public View getView(int p,View v,ViewGroup g){LinearLayout box=new LinearLayout(IslamicCatalogActivity.this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(6,6,6,8);box.setBackgroundColor(Color.rgb(11,29,51));ImageView im=new ImageView(IslamicCatalogActivity.this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);box.addView(im,new LinearLayout.LayoutParams(-1,210));TextView t=new TextView(IslamicCatalogActivity.this);t.setText(fin.get(p).title);t.setTextColor(Color.WHITE);t.setTextSize(15);t.setGravity(Gravity.CENTER);t.setMaxLines(2);box.addView(t,new LinearLayout.LayoutParams(-1,60));String u=fin.get(p).poster;if(u!=null&&!u.isEmpty())loadImage(im,u);return box;}});grid.setOnItemClickListener((x,v,p,id)->open(fin.get(p),raw));status.setText(items.size()+" materiale");}
 private void open(Item i,ArrayList<Item>raw){if("series".equals(i.type)&&!"source".equals(i.source)){ArrayList<Item>eps=new ArrayList<>();for(Item e:raw)if(seriesKey(e).equals(i.id))eps.add(e);String[] names=new String[eps.size()];for(int n=0;n<eps.size();n++)names[n]=(eps.get(n).episode>0?eps.get(n).episode+". ":"")+eps.get(n).title;new AlertDialog.Builder(this).setTitle(i.title).setItems(names,(d,w)->openWeb(eps.get(w).url,eps.get(w).title)).show();}else openWeb(i.url,i.title);}
 private void openWeb(String u,String title){Intent x=new Intent(this,EmbeddedWebActivity.class);x.putExtra("url",u);x.putExtra("title",title);startActivity(x);}
 private String seriesKey(Item i){if("source".equals(i.source))return i.id;if(i.id.startsWith("OMERI_RA_"))return"OMERI_RA";if(i.id.startsWith("AHMED_IBN_HAMBEL_"))return"AHMED_IBN_HAMBEL";return i.id.replaceAll("_[0-9]+$","");}
 private String seriesTitle(Item i){if("OMERI_RA".equals(seriesKey(i)))return"Omeri r.a.";if("AHMED_IBN_HAMBEL".equals(seriesKey(i)))return"Ahmed ibn Hambeli";return i.title.replaceAll("(?i)\\s*[-–]\\s*(Epizodi|Pjesa)\\s*\\d+.*$","");}
 private String posterFor(String id){String b="https://raw.githubusercontent.com/iljazsalihi95-wq/LazyTV-Android/main/cms/posters/";if(id.contains("MERYEM"))return b+"poster_meryem.webp";if(id.contains("ASHABUL"))return b+"poster_ashabul_kehf.webp";if(id.contains("ISA"))return b+"poster_isa.webp";if(id.contains("ZEKERIJA"))return b+"lect_zekerija_bajrami.webp";if(id.contains("OMER_DAUTI"))return b+"lect_omer_dauti.webp";if(id.contains("BESIM"))return b+"lect_besim_luma.webp";if(id.contains("JAKUP"))return b+"lect_jakup_hasipi.webp";if(id.contains("SHEFQET"))return b+"lect_shefqet_krasniqi.webp";if(id.contains("ARDIAN"))return b+"lect_ardian_sejdiu.webp";if(id.contains("RAMADAN"))return b+"lect_ramadan_ramadani.webp";return"";}
 private String posterForUrl(String u){try{if(u==null)return"";if(u.contains("youtu.be/")){String id=u.substring(u.indexOf("youtu.be/")+9).split("[?&]")[0];return"https://img.youtube.com/vi/"+id+"/hqdefault.jpg";}if(u.contains("youtube.com/watch")){String q=new URL(u).getQuery();if(q!=null)for(String p:q.split("&"))if(p.startsWith("v="))return"https://img.youtube.com/vi/"+p.substring(2)+"/hqdefault.jpg";}if(u.contains("dailymotion.com/video/")){String id=u.substring(u.indexOf("/video/")+7).split("[?_/#]")[0];return"https://www.dailymotion.com/thumbnail/video/"+id;}if(u.contains("dai.ly/")){String id=u.substring(u.indexOf("dai.ly/")+7).split("[?_/#]")[0];return"https://www.dailymotion.com/thumbnail/video/"+id;}if(u.contains("archive.org/details/")){String id=u.substring(u.indexOf("/details/")+9).split("[?/#]")[0];return"https://archive.org/services/img/"+id;}}catch(Exception ignored){}return"";}
 private void loadImage(ImageView v,String u){pool.execute(()->{try{Bitmap b=BitmapFactory.decodeStream(new URL(u).openStream());runOnUiThread(()->v.setImageBitmap(b));}catch(Exception ignored){}});}
 private static int num(String s){try{return Integer.parseInt(s);}catch(Exception e){return 0;}}
 private static String label(String c){if(IslamicCmsConfig.FILMS.equals(c))return"Filma Islam";if(IslamicCmsConfig.SERIES.equals(c))return"Filma Serik Islam";if(IslamicCmsConfig.LECTURES.equals(c))return"Ligjërata Islame";if(IslamicCmsConfig.DOCUMENTARIES.equals(c))return"Dokumentare Islame";if(IslamicCmsConfig.KIDS.equals(c))return"Filma Vizatimor Islam";return"LazyTV PRO";}
 private static List<String[]> csv(String u)throws Exception{ArrayList<String[]>o=new ArrayList<>();BufferedReader b=new BufferedReader(new InputStreamReader(new URL(u).openStream(),"UTF-8"));String l;boolean first=true;while((l=b.readLine())!=null){if(first){first=false;continue;}o.add(parse(l));}b.close();return o;}
 private static String[] parse(String s){ArrayList<String>a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='"'){b.append('"');i++;}else q=!q;}else if(c==','&&!q){a.add(b.toString());b.setLength(0);}else b.append(c);}a.add(b.toString());return a.toArray(new String[0]);}
 protected void onDestroy(){pool.shutdownNow();super.onDestroy();}
}