package de.lazytv.pro.activation;
import android.content.*;import android.os.SystemClock;import android.security.keystore.*;import java.nio.charset.StandardCharsets;import java.security.*;import javax.crypto.*;
public final class ActivationCache {
 private static final String PREF="activation_cache_v1",KEY="lazytv_activation_hmac_v1";private final SharedPreferences p;
 public ActivationCache(Context c){p=c.getSharedPreferences(PREF,Context.MODE_PRIVATE);}
 public void save(ActivationResult r){long elapsed=SystemClock.elapsedRealtime();String data=r.status.name()+"|"+r.expiresAtMs+"|"+r.serverTimeMs+"|"+elapsed;String sig=sign(data);if(sig.isEmpty()){p.edit().clear().apply();return;}p.edit().putString("status",r.status.name()).putLong("expires",r.expiresAtMs).putLong("server",r.serverTimeMs).putLong("elapsed",elapsed).putString("sig",sig).apply();}
 public Snapshot read(){String st=p.getString("status","");long ex=p.getLong("expires",0),sv=p.getLong("server",0),el=p.getLong("elapsed",-1);String sig=p.getString("sig","");ActivationStatus s=ActivationStatus.parse(st);String expected=sign(st+"|"+ex+"|"+sv+"|"+el);if(s==null||el<0||sig.isEmpty()||expected.isEmpty()||!constant(sig,expected))return null;return new Snapshot(s,ex,sv,el);}
 public boolean validOfflineGrace(long graceMs){Snapshot s=read();if(s==null||(s.status!=ActivationStatus.ACTIVE&&s.status!=ActivationStatus.TRIAL))return false;long nowElapsed=SystemClock.elapsedRealtime();if(nowElapsed<s.elapsedAtCheck)return false;long delta=nowElapsed-s.elapsedAtCheck;if(delta>graceMs)return false;long estimated=s.serverTimeMs+delta;return s.expiresAtMs<=0||estimated<s.expiresAtMs;}
 public static final class Snapshot{public final ActivationStatus status;public final long expiresAtMs,serverTimeMs,elapsedAtCheck;Snapshot(ActivationStatus s,long e,long t,long l){status=s;expiresAtMs=e;serverTimeMs=t;elapsedAtCheck=l;}}
 private static boolean constant(String a,String b){return a!=null&&b!=null&&MessageDigest.isEqual(a.getBytes(StandardCharsets.UTF_8),b.getBytes(StandardCharsets.UTF_8));}
 private static String sign(String data){try{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(!ks.containsAlias(KEY)){KeyGenerator kg=KeyGenerator.getInstance("HmacSHA256","AndroidKeyStore");kg.init(new KeyGenParameterSpec.Builder(KEY,KeyProperties.PURPOSE_SIGN|KeyProperties.PURPOSE_VERIFY).setDigests(KeyProperties.DIGEST_SHA256).build());kg.generateKey();}Mac m=Mac.getInstance("HmacSHA256");m.init((java.security.Key)ks.getKey(KEY,null));byte[]v=m.doFinal(data.getBytes(StandardCharsets.UTF_8));return android.util.Base64.encodeToString(v,android.util.Base64.NO_WRAP);}catch(Exception e){return "";}}
}
