package de.lazytv.pro.activation;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import de.lazytv.pro.*;import java.text.*;import java.util.*;import java.util.concurrent.*;
public class ActivationActivity extends Activity {
 public static final String EXTRA_ERROR="activation_error";private final ExecutorService pool=Executors.newSingleThreadExecutor();private DeviceIdentityManager id;private TextView status,expires;private Button check,refresh;private volatile boolean destroyed;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_activation);id=new DeviceIdentityManager(this);((TextView)findViewById(R.id.device_id)).setText(id.getDeviceId()+"\n"+id.getLazyTvId());((TextView)findViewById(R.id.serial)).setText(id.getSerial());status=findViewById(R.id.activation_status);expires=findViewById(R.id.activation_expiration);check=findViewById(R.id.check_activation);refresh=findViewById(R.id.refresh_activation);findViewById(R.id.copy_device).setOnClickListener(v->copy("Device ID",id.getDeviceId()+" / "+id.getLazyTvId()));findViewById(R.id.copy_serial).setOnClickListener(v->copy("Serial",id.getSerial()));check.setOnClickListener(v->doCheck());refresh.setOnClickListener(v->doCheck());String err=getIntent().getStringExtra(EXTRA_ERROR);showCached(err);}
 private void showCached(String error){ActivationCache.Snapshot s=new ActivationCache(this).read();if(error!=null&&!error.isEmpty())status.setText(error);else if(s==null)status.setText("INACTIVE — Waiting for activation");else status.setText(label(s.status));expires.setText(s!=null&&s.expiresAtMs>0?"Activated until / Aktiv bis / Aktiv deri më: "+format(s.expiresAtMs):"");}
 private void doCheck(){String base=BuildConfig.ACTIVATION_BASE_URL;if(base==null||base.trim().isEmpty()){status.setText("Activation service not configured");return;}setBusy(true);pool.execute(()->{try{ActivationResult r=new ActivationApiClient().check(base,id.getDeviceId(),id.getSerial(),id.getLazyTvId(),BuildConfig.VERSION_NAME);new ActivationCache(this).save(r);runOnUiThread(()->{if(destroyed||isFinishing())return;setBusy(false);status.setText(label(r.status));expires.setText(r.expiresAtMs>0?"Activated until / Aktiv bis / Aktiv deri më: "+format(r.expiresAtMs):"");if(r.status==ActivationStatus.ACTIVE){startActivity(new Intent(this,MainActivity.class));finish();}});}catch(ActivationApiClient.ActivationException e){runOnUiThread(()->{if(destroyed||isFinishing())return;setBusy(false);status.setText(e.getMessage());});}});}
 private String label(ActivationStatus s){switch(s){case ACTIVE:return"ACTIVE";case EXPIRED:return"EXPIRED — Activation has expired";case BLOCKED:return"This device is blocked.";default:return"INACTIVE — Waiting for activation";}}
 private String format(long ms){return DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(ms));}private void setBusy(boolean b){check.setEnabled(!b);refresh.setEnabled(!b);status.setText(b?"Checking activation…":status.getText());}
 private void copy(String label,String text){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(label,text));Toast.makeText(this,"Copied",Toast.LENGTH_SHORT).show();}
 @Override protected void onDestroy(){destroyed=true;pool.shutdownNow();super.onDestroy();}
}
