package de.lazytv.pro.activation;
import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import javax.net.ssl.HttpsURLConnection;
public final class ActivationApiClient {
 public static class ActivationException extends Exception{public final boolean network;ActivationException(String m,boolean n){super(m);network=n;}}
 public ActivationResult check(String base,String deviceId,String serial,String lazyTvId,String appVersion)throws ActivationException{
  if(base==null||base.trim().isEmpty())throw new ActivationException("Activation service not configured",false);
  String clean=base.trim();if(!clean.toLowerCase(java.util.Locale.US).startsWith("https://"))throw new ActivationException("Activation service requires HTTPS",false);
  HttpsURLConnection c=null;try{URL u=new URL(clean.replaceAll("/+$","")+"/api/v1/device/check");c=(HttpsURLConnection)u.openConnection();c.setConnectTimeout(10000);c.setReadTimeout(12000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.setRequestProperty("Accept","application/json");JSONObject q=new JSONObject();q.put("device_id",deviceId);q.put("serial",serial);q.put("lazytv_id",lazyTvId);q.put("app_version",appVersion);byte[]body=q.toString().getBytes(StandardCharsets.UTF_8);try(OutputStream o=c.getOutputStream()){o.write(body);}int code=c.getResponseCode();if(code<200||code>=300)throw new ActivationException("Activation service error",true);String ct=c.getContentType();if(ct!=null&&!ct.toLowerCase(java.util.Locale.US).contains("json"))throw new ActivationException("Invalid activation response",false);String text=read(c.getInputStream());JSONObject j=new JSONObject(text);ActivationStatus s=ActivationStatus.parse(j.optString("status",null));if(s==null)throw new ActivationException("Invalid activation status",false);long server=parseTime(j.optString("server_time",null));if(server<=0)throw new ActivationException("Invalid activation server time",false);long exp=parseTime(j.optString("expires_at",null));if(s==ActivationStatus.ACTIVE&&exp>0&&exp<=server)s=ActivationStatus.EXPIRED;return new ActivationResult(s,exp,server,j.optString("message",""));
  }catch(ActivationException e){throw e;}catch(SocketTimeoutException e){throw new ActivationException("Activation request timed out",true);}catch(IOException e){throw new ActivationException("Activation service unavailable",true);}catch(Exception e){throw new ActivationException("Invalid activation response",false);}finally{if(c!=null)c.disconnect();}}
 private static String read(InputStream in)throws IOException{try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null){if(b.length()>65536)throw new IOException("Response too large");b.append(x);}return b.toString();}}
 private static long parseTime(String s){if(s==null||s.trim().isEmpty())return 0;try{java.text.SimpleDateFormat f=new java.text.SimpleDateFormat("yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'",java.util.Locale.US);f.setTimeZone(java.util.TimeZone.getTimeZone("UTC"));return f.parse(s).getTime();}catch(Exception ignored){}try{java.text.SimpleDateFormat f=new java.text.SimpleDateFormat("yyyy-MM-dd\'T\'HH:mm:ss\'Z\'",java.util.Locale.US);f.setTimeZone(java.util.TimeZone.getTimeZone("UTC"));return f.parse(s).getTime();}catch(Exception ignored){}try{return Long.parseLong(s);}catch(Exception ignored){return 0;}}
}
