package de.lazytv.pro;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;import de.lazytv.pro.live.LiveTvActivity;import de.lazytv.pro.playlist.*;

public class MainActivity extends Activity{
 private TextView location,weather,clock,prayer;private LinearLayout rail;
 @Override protected void onCreate(Bundle b){super.onCreate(b);buildHome();}
 private void buildHome(){boolean portrait=getResources().getConfiguration().orientation==android.content.res.Configuration.ORIENTATION_PORTRAIT;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(10),dp(14),dp(10));root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(2,8,26),Color.rgb(8,44,78),Color.rgb(2,14,34)}));
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView brand=text("LazyTV PRO",portrait?22:28,Color.WHITE,true);top.addView(brand,new LinearLayout.LayoutParams(0,dp(52),1));location=text("⌖ GPS",13,Color.rgb(150,220,255),true);weather=text("☁ --°C",13,Color.WHITE,true);clock=text(now(),18,Color.WHITE,true);top.addView(location,new LinearLayout.LayoutParams(dp(portrait?125:190),dp(52)));top.addView(weather,new LinearLayout.LayoutParams(dp(90),dp(52)));top.addView(clock,new LinearLayout.LayoutParams(dp(72),dp(52)));root.addView(top);
  LinearLayout utility=new LinearLayout(this);utility.setGravity(Gravity.CENTER_VERTICAL);TextView date=text(new java.text.SimpleDateFormat("EEE, dd.MM.yyyy",Locale.getDefault()).format(new Date()),12,Color.rgb(120,190,235),false);utility.addView(date,new LinearLayout.LayoutParams(0,dp(38),1));prayer=text("🕌 Namazi",12,Color.rgb(255,201,92),true);prayer.setGravity(Gravity.CENTER);card(prayer,Color.rgb(7,38,64));utility.addView(prayer,new LinearLayout.LayoutParams(dp(110),dp(34)));root.addView(utility);
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);rail=new LinearLayout(this);rail.setOrientation(LinearLayout.HORIZONTAL);rail.setGravity(Gravity.CENTER_VERTICAL);String[] names={"LIVE TV","PREMIUM","MOVIES","SERIES","PLAYLISTS","CATCH-UP","FAVORITES","SETTINGS","RELOAD","SERVERS","EXIT"};Button[] bs=new Button[names.length];for(int i=0;i<names.length;i++){bs[i]=tile(names[i]);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(portrait?132:158),dp(portrait?126:150));lp.setMargins(dp(6),dp(12),dp(6),dp(12));rail.addView(bs[i],lp);}hs.addView(rail);root.addView(hs,new LinearLayout.LayoutParams(-1,0,1));
  Playlist a=active();TextView footer=text("ACTIVE PROVIDER  •  "+(a==null?"FREE TV":a.getName()),11,Color.rgb(145,200,230),false);root.addView(footer,new LinearLayout.LayoutParams(-1,dp(28)));setContentView(root);
  bs[0].setOnClickListener(v->openLive());bs[1].setOnClickListener(v->openServerTen());bs[2].setOnClickListener(v->openCatalog("MOVIES"));bs[3].setOnClickListener(v->openCatalog("SERIES"));bs[4].setOnClickListener(v->openPlaylists());bs[5].setOnClickListener(v->Toast.makeText(this,"Catch-up aktivizohet kur provider-i ofron arkivë",Toast.LENGTH_LONG).show());bs[6].setOnClickListener(v->openCatalog(null));bs[7].setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));bs[8].setOnClickListener(v->reload());bs[9].setOnClickListener(v->showServers());bs[10].setOnClickListener(v->finish());prayer.setOnClickListener(v->showPrayer());bs[0].requestFocus();updateLocal();}
 private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER_VERTICAL);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);return t;}
 private Button tile(String s){Button b=new Button(this);b.setText(icon(s)+"\n"+s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setFocusable(true);b.setFocusableInTouchMode(true);style(b,false,s);b.setOnFocusChangeListener((v,f)->{v.animate().scaleX(f?1.08f:1f).scaleY(f?1.08f:1f).setDuration(110).start();style((Button)v,f,s);if(f&&v.getParent() instanceof LinearLayout){final View x=v;v.post(()->x.getParent().requestChildFocus(x,x));}});return b;}
 private String icon(String s){if(s.equals("LIVE TV"))return "▣";if(s.equals("PREMIUM"))return "★";if(s.equals("MOVIES"))return "●";if(s.equals("SERIES"))return "▤";if(s.equals("FAVORITES"))return "♥";if(s.equals("SETTINGS"))return "⚙";if(s.equals("RELOAD"))return "↻";if(s.equals("SERVERS"))return "☷";if(s.equals("EXIT"))return "⇥";return "▦";}
 private void style(Button b,boolean f,String s){int accent=s.equals("PREMIUM")||s.equals("SERVERS")?Color.rgb(245,164,45):s.equals("MOVIES")||s.equals("FAVORITES")?Color.rgb(214,54,87):s.equals("SERIES")?Color.rgb(133,65,190):Color.rgb(0,124,194);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,f?new int[]{accent,Color.rgb(4,42,73)}:new int[]{Color.rgb(8,42,69),Color.rgb(3,18,35)});g.setCornerRadius(dp(20));g.setStroke(dp(f?3:1),f?Color.WHITE:Color.rgb(34,79,112));b.setBackground(g);b.setElevation(dp(f?12:3));}
 private void card(View v,int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(14));g.setStroke(dp(1),Color.rgb(38,112,150));v.setBackground(g);}
 private void openLive(){Playlist p=active();Intent i=new Intent(this,LiveTvActivity.class);if(p!=null){i.putExtra("playlist_id",p.getId());i.putExtra("source_scope","PROVIDER");}else{i.putExtra("builtin_live",true);i.putExtra("source_scope","TRIAL");}startActivity(i);}
 private void openServerTen(){Intent i=new Intent(this,LiveTvActivity.class);i.putExtra("source_scope","SERVER_10");i.putExtra("server_id","SERVER_10");startActivity(i);}
 private void showServers(){PlaylistStorage s=new PlaylistStorage(this);List<Playlist>a=s.getAll();String[] names=new String[a.size()+1];names[0]="Premium • Server 10 • MANAGED";for(int n=0;n<a.size();n++)names[n+1]=a.get(n).getName()+" • "+a.get(n).getType().name();new AlertDialog.Builder(this).setTitle("Servers / Providers").setItems(names,(d,w)->{if(w==0){openServerTen();return;}Playlist p=a.get(w-1);s.setActive(p.getId());recreate();}).setPositiveButton("Manage",(d,w)->openPlaylists()).show();}
 private Playlist active(){PlaylistStorage s=new PlaylistStorage(this);String id=s.getActiveId();return id==null?null:s.get(id);}private void openPlaylists(){startActivity(new Intent(this,PlaylistManagerActivity.class));}
 private void openCatalog(String type){Playlist p=active();if(p==null){openPlaylists();return;}Intent i=new Intent(this,de.lazytv.pro.catalog.CatalogActivity.class);i.putExtra("playlist_id",p.getId());i.putExtra("source_scope","PROVIDER");if(type!=null)i.putExtra(de.lazytv.pro.catalog.CatalogActivity.EXTRA_TYPE,type);startActivity(i);}
 private void reload(){Playlist p=active();if(p==null){openPlaylists();return;}Intent i=new Intent(this,LiveTvActivity.class);i.putExtra("playlist_id",p.getId());i.putExtra("source_scope","PROVIDER");i.putExtra("force_reload",true);startActivity(i);}
 private void updateLocal(){String saved=getSharedPreferences("lazytv_local",MODE_PRIVATE).getString("city","");if(!saved.isEmpty())location.setText("⌖ "+saved);if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION},41);return;}try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location l=lm==null?null:lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(l==null&&lm!=null)l=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(l!=null){Location x=l;new Thread(()->loadLocal(x)).start();}}catch(Exception ignored){}}
 private void loadLocal(Location l){String city="GPS";try{List<android.location.Address>a=new Geocoder(this,Locale.getDefault()).getFromLocation(l.getLatitude(),l.getLongitude(),1);if(a!=null&&!a.isEmpty()){android.location.Address x=a.get(0);String cc=x.getCountryCode()==null?"":x.getCountryCode();city=(cc.isEmpty()?"":flag(cc)+" ")+(x.getLocality()==null?"GPS":x.getLocality());}}catch(Exception ignored){}String c=city;runOnUiThread(()->{location.setText("⌖ "+c);getSharedPreferences("lazytv_local",MODE_PRIVATE).edit().putString("city",c).apply();});}
 private String flag(String cc){if(cc==null||cc.length()!=2)return"";int a=Character.codePointAt(cc.toUpperCase(Locale.ROOT),0)-'A'+0x1F1E6,b=Character.codePointAt(cc.toUpperCase(Locale.ROOT),1)-'A'+0x1F1E6;return new String(Character.toChars(a))+new String(Character.toChars(b));}
 private void showPrayer(){new AlertDialog.Builder(this).setTitle("🕌 Kohët e Namazit").setMessage("Kohët e namazit shfaqen sipas vendndodhjes së pajisjes. Moduli i plotë i kohëve ruhet i ndarë nga Home për të mos përdorur marquee.").setPositiveButton("OK",null).show();}
 private String now(){return new java.text.SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date());}@Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==41)updateLocal();}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}
