package de.lazytv.pro.playlist;
import android.content.Context;import android.content.SharedPreferences;import org.json.JSONArray;import org.json.JSONException;import java.util.*;
public class PlaylistStorage {
 private static final String PREFS="lazytv_playlists",KEY_ITEMS="items",KEY_ACTIVE="active_playlist_id",FREE_ID="builtin-free-tv";
 private final SharedPreferences prefs;
 public PlaylistStorage(Context context){prefs=context.getSharedPreferences(PREFS,Context.MODE_PRIVATE);}
 private Playlist freeTv(){return new Playlist(FREE_ID,"FREE TV",PlaylistType.FREE_TV,"","","","",0L);}
 public List<Playlist> getAll(){List<Playlist> result=new ArrayList<>();String raw=prefs.getString(KEY_ITEMS,"[]");try{JSONArray array=new JSONArray(raw);for(int i=0;i<array.length();i++){try{result.add(Playlist.fromJson(array.getJSONObject(i)));}catch(Exception ignored){}}}catch(Exception ignored){}boolean hasFree=false;for(Playlist p:result)if(p.getType()==PlaylistType.FREE_TV||FREE_ID.equals(p.getId())){hasFree=true;break;}if(!hasFree)result.add(freeTv());Collections.sort(result,(a,b)->{if(a.getType()==PlaylistType.FREE_TV&&b.getType()!=PlaylistType.FREE_TV)return 1;if(b.getType()==PlaylistType.FREE_TV&&a.getType()!=PlaylistType.FREE_TV)return -1;return Long.compare(b.getUpdatedAt(),a.getUpdatedAt());});return result;}
 public Playlist get(String id){if(id==null)return null;for(Playlist playlist:getAll())if(id.equals(playlist.getId()))return playlist;return null;}
 public void save(Playlist item){if(item==null)throw new IllegalArgumentException("Playlist is required");if(item.getType()==PlaylistType.FREE_TV)return;List<Playlist> items=persistedOnly();boolean replaced=false;for(int i=0;i<items.size();i++)if(items.get(i).getId().equals(item.getId())){items.set(i,item);replaced=true;break;}if(!replaced)items.add(item);write(items);}
 public void delete(String id){if(id==null||FREE_ID.equals(id))return;List<Playlist> items=persistedOnly();for(int i=items.size()-1;i>=0;i--)if(id.equals(items.get(i).getId()))items.remove(i);write(items);if(id.equals(getActiveId()))prefs.edit().remove(KEY_ACTIVE).apply();}
 public void setActive(String id){if(get(id)==null)throw new IllegalArgumentException("Playlist does not exist");prefs.edit().putString(KEY_ACTIVE,id).apply();}
 public String getActiveId(){String id=prefs.getString(KEY_ACTIVE,"");if(id!=null&&getWithoutActiveLookup(id)!=null)return id;List<Playlist> items=getAll();if(items.isEmpty())return FREE_ID;String recovered=items.get(0).getId();prefs.edit().putString(KEY_ACTIVE,recovered).apply();return recovered;}
 public Playlist getActive(){String id=getActiveId();return id.isEmpty()?null:getWithoutActiveLookup(id);}
 private Playlist getWithoutActiveLookup(String id){if(id==null||id.isEmpty())return null;if(FREE_ID.equals(id))return freeTv();for(Playlist playlist:getAll())if(id.equals(playlist.getId()))return playlist;return null;}
 private List<Playlist> persistedOnly(){List<Playlist> out=new ArrayList<>();String raw=prefs.getString(KEY_ITEMS,"[]");try{JSONArray array=new JSONArray(raw);for(int i=0;i<array.length();i++){try{Playlist p=Playlist.fromJson(array.getJSONObject(i));if(p.getType()!=PlaylistType.FREE_TV&&!FREE_ID.equals(p.getId()))out.add(p);}catch(Exception ignored){}}}catch(Exception ignored){}return out;}
 private void write(List<Playlist> items){JSONArray array=new JSONArray();try{for(Playlist playlist:items)if(playlist.getType()!=PlaylistType.FREE_TV)array.put(playlist.toJson());boolean ok=prefs.edit().putString(KEY_ITEMS,array.toString()).commit();if(!ok)throw new IllegalStateException("Playlist storage write failed");}catch(JSONException e){throw new IllegalStateException("Playlist serialization failed",e);}}
}
